server:
  servlet:
    context-path: /assessment
spring:
  activemq:
      broker-url: vm://localhost?broker.persistent=false&broker.useShutdownHook=false
      in-memory: true
      non-blocking-redelivery: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  datasource:
    initialization-mode: always
    data: classpath:sql/prepopulation-data.sql
logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
    springfox: INFO
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
  api-docs:
    path: /api-docs
ing:
  user:
    save:
      topic: user_save_topic
    update:
      topic: user_update_topic
datasource:
  db:
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:testdb
    username: sa
    password: password
    minPool: 2
    maxPool: 20